name: deploy

on:
  push:
    branches: [main]

jobs:
  call:
    uses: Arcanada-one/shared-workflows/.github/workflows/deploy-static-site.yml@fc81443c3c6e206feda41fd95b4952a2e2189a51 # v1
    with:
      domain: arcanada.wiki
      webroot: arcanada.wiki
    secrets: inherit
