name: deploy

on:
  push:
    branches: [main]

jobs:
  call:
    uses: Arcanada-one/shared-workflows/.github/workflows/deploy-static-site.yml@v1
    with:
      domain: arcanada.wiki
      webroot: arcanada.wiki
    secrets: inherit
